
### CV vs Undersmoothing (Zero smoothness order with default number of knots)

```{r}
load(here("data", "rdata", paste0("02_simu_V5_sys", sn, "_", nn, "_default.RData")))

results_0$result_summary = add_bound(results_0$result_summary)

rslt_sum_default = results_0$result_summary

cv_lambda = unique(rslt_sum_default$lambda[rslt_sum_default$method == 'CV'])
u_g_lambda = unique(rslt_sum_default$lambda[rslt_sum_default$method == 'U_G'])
u_g_scaler = unique(rslt_sum_default$lambda_scaler[rslt_sum_default$method == 'U_G'])

eval_points = seq(0,5,0.5)

cv_n_bases = unique(rslt_sum_default$n_basis[rslt_sum_default$method == 'CV'])
u_g_n_bases = unique(rslt_sum_default$n_basis[rslt_sum_default$method == 'U_G'])

cat(sprintf(' The average lambda of CV-HAL: %0.4f (= 1 * lambda_CV )', cv_lambda))
cat(sprintf(' The average lambda of globally undersmoothed HAL: %0.4f (= %0.4f * lambda_CV )', u_g_lambda, u_g_scaler))

cat(sprintf(' The average number of bases of CV-HAL: %0.4f ', cv_n_bases))
cat(sprintf(' The average number of bases of globally undersmoothed HAL: %0.4f ', u_g_n_bases))


cat(sprintf(' The average fitting time for CV-HAL: %0.4f seconds', mean(rslt_sum_default$hal_fit_time[rslt_sum_default$method=='CV'])))
cat(sprintf(' The average fitting time for globally undersmoothed HAL: %0.4f seconds', mean(rslt_sum_default$hal_fit_time[rslt_sum_default$method=='U_G'])))


```

```{r fig.height=9, fig.width=9}
p <- plot_performences_cv_ug_alla_noBT(df = rslt_sum_default, save_plot = here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_performences_default.png")))

```
```{r fig.height=4, fig.width=12}
p <- estimation_qqplot_cv_ug_alla(results_list = results_0, save_plot = here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_QQplots_default.png")))
plot(p)
```


### Undersmoothed Smoothness-adaptive HAL
```{r fig.width=8, fig.height=12}
load(here("data", "rdata", paste0("02_simu_V5_sys", sn, "_", nn, "_adapt.RData")))

results_adapt1 = summary_smoothness_adaptive_HAL(results_adapt$result_list)
results_adapt1$result_summary = add_bound(results_adapt1$result_summary)

p <- plot_performences_adapt(df = results_adapt1$result_summary,
                             save_plot=here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_adapt_performences.png")))

```

```{r}
df_adapt_n_basis = unique(results_adapt1$result_summary[, c('smooth_order', 'if_n_knots_default', 'sl_pick', 'lambda', 'lambda_scaler', 'n_basis', 'cv_risk')])

df_adapt_n_basis = round(df_adapt_n_basis, 4)
df_adapt_n_basis$if_n_knots_default = factor(df_adapt_n_basis$if_n_knots_default)
print(df_adapt_n_basis)


df_adapt_n_basis$label_val = as.character(round(df_adapt_n_basis$n_basis, 2)) 
df_adapt_n_basis$lambda_val = as.character(round(df_adapt_n_basis$lambda, 2)) 
df_adapt_n_basis$cv_risk_val = as.character(round(df_adapt_n_basis$cv_risk, 2)) 


p_n_basis_grid <- ggplot(df_adapt_n_basis, aes(x = smooth_order, color = if_n_knots_default)) +  
      geom_line(aes(y = n_basis, color = if_n_knots_default)) + 
      geom_point(aes(y = n_basis, color = if_n_knots_default)) + 
  geom_text(aes(y = n_basis, label = label_val), hjust=0, vjust=0) + 
      theme_bw()  + 
      labs(x = "smooth order", y = "Number of bases") 
p_n_basis_grid
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_adapt_num_basis.png")), plot=p_n_basis_grid, width = 5, height = 3,  dpi = 800)

p_lambda_grid <- ggplot(df_adapt_n_basis, aes(x = smooth_order, color = if_n_knots_default)) +  
      geom_line(aes(y = lambda, color = if_n_knots_default)) + 
      geom_point(aes(y = lambda, color = if_n_knots_default)) + 
  geom_text(aes(y = lambda, label = lambda_val), hjust=0, vjust=0) + 
      theme_bw()  + 
      labs(x = "smooth order", y = "lambda") 
p_lambda_grid
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_adapt_lambda.png")), plot=p_lambda_grid, width = 5, height = 3,  dpi = 800)

p_cv_risk_grid <- ggplot(df_adapt_n_basis, aes(x = smooth_order, color = if_n_knots_default)) +  
      geom_line(aes(y = cv_risk, color = if_n_knots_default)) + 
      geom_point(aes(y = cv_risk, color = if_n_knots_default)) + 
  geom_text(aes(y = cv_risk, label = cv_risk_val), hjust=0, vjust=0) + 
      theme_bw()  + 
      labs(x = "smooth order", y = "CV risk") 
p_cv_risk_grid
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_adapt_cv_risk.png")), plot=p_cv_risk_grid, width = 5, height = 3,  dpi = 800)
```


### CV vs Undersmoothing (First smoothness order with smaller number of knots)
```{r}
load(here("data", "rdata", paste0("02_simu_V5_sys", sn, "_", nn, ".RData")))

results$result_summary = add_bound(results$result_summary)

rslt_sum = results$result_summary

cv_lambda = unique(rslt_sum$lambda[rslt_sum$method == 'CV'])
u_g_lambda = unique(rslt_sum$lambda[rslt_sum$method == 'U_G'])
u_g_scaler = unique(rslt_sum$lambda_scaler[rslt_sum$method == 'U_G'])

eval_points = seq(0,5,0.5)

cv_n_bases = unique(rslt_sum$n_basis[rslt_sum$method == 'CV'])
u_g_n_bases = unique(rslt_sum$n_basis[rslt_sum$method == 'U_G'])

cat(sprintf(' The average lambda of CV-HAL: %0.4f (= 1 * lambda_CV )', cv_lambda))
cat(sprintf(' The average lambda of globally undersmoothed HAL: %0.4f (= %0.4f * lambda_CV )', u_g_lambda, u_g_scaler))

cat(sprintf(' The average number of bases of CV-HAL: %0.4f ', cv_n_bases))
cat(sprintf(' The average number of bases of globally undersmoothed HAL: %0.4f ', u_g_n_bases))


cat(sprintf(' The average fitting time for CV-HAL: %0.4f seconds', mean(rslt_sum$hal_fit_time[rslt_sum$method=='CV'])))
cat(sprintf(' The average fitting time for globally undersmoothed HAL: %0.4f seconds', mean(rslt_sum$hal_fit_time[rslt_sum$method=='U_G'])))


```

```{r fig.height=9, fig.width=9}
p <- plot_performences_cv_ug_alla_noBT(df = rslt_sum, save_plot = here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_performences.png")))
```
```{r fig.height=4, fig.width=12}
p <- estimation_qqplot_cv_ug_alla(results_list = results, save_plot = here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_QQplots.png")))
plot(p)
```


### grid of scalers
```{r fig.width=25, fig.height=11}

lambda_scalers = c(1.2, 1.1, 10^seq(from=0, to=-3, length=20))

load(here("data", "rdata", paste0("02_simu_V5_sys", sn, "_", nn, "_grid.RData")))

results_grid_s <- results_grid_summary(results_grid)
results_grid_s = add_bound(results_grid_s)


p <- plot_perforences_alllambda_noBT(results_grid_s,
                                u_g_scaler=u_g_scaler, 
                                save_plot=here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_grid_performences.png")), 
                                max_bias_sd=NA)

no_empirical_CI_proportion <- results_grid$no_empirical_CI_proportion
names(no_empirical_CI_proportion) = as.character(round(lambda_scalers,4))
print("proportion of simulations that cannot compute empirical SD:")
print(no_empirical_CI_proportion)
```

```{r}
df_grid_n_basis = unique(results_grid_s[, c('lambda_scaler', 'n_basis')])

cv_n_b = mean(df_grid_n_basis$n_basis[df_grid_n_basis$lambda_scaler == 1])
u_g_n_b = mean(df_grid_n_basis$n_basis[which(abs(df_grid_n_basis$lambda_scaler - u_g_scaler) == min(abs(df_grid_n_basis$lambda_scaler - u_g_scaler) ))])

p_n_basis_grid <- ggplot(df_grid_n_basis, aes(x = lambda_scaler)) +  
      geom_line(aes(y = n_basis)) + 
      geom_point(aes(y = n_basis)) + 
      theme_bw()  + 
      labs(x = "lambda scalers", y = "Number of bases") +
      theme(legend.position='none') +
        geom_vline(xintercept = u_g_scaler, lty=2, col = "#00BA38") +
        geom_vline(xintercept = 1, lty=2, col = "#F8766D") + 
     annotate(x=u_g_scaler, y=+Inf, label=round(u_g_n_b, 2), vjust=2, geom="label") +
     annotate(x=1, y=+Inf, label=round(cv_n_b, 2), vjust=2, geom="label")


p_n_basis_grid

ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_grid_num_basis.png")), plot=p_n_basis_grid, width = 5, height = 3,  dpi = 800)
```

### vs GAM & Polynomial regression
```{r}
load(here("data", "rdata", paste0("02_simu_V5_sys", sn, "_", nn, "_poly.RData")))
load(here("data", "rdata", paste0("02_simu_V5_sys", sn, "_", nn, "_GAM.RData")))

results_poly$result_summary$method = "Poly"
results_adapt1 = add_bound(results_adapt1)

results_df1 = results_0$result_summary[results_0$result_summary$method == "U_G",]
results_df1$method = "U_G_0SO_dft"
results_df2 = results_adapt1$result_summary[results_adapt1$result_summary$method == "U_HAL_SL_pick", ]
results_df2$method = "U_SOadapt"

colnames_overlap = intersect( intersect(names(results_df1), names(results_df2)), names(results_poly$result_summary))

results_all <- rbind(results_gam$result_summary[, colnames_overlap], 
                     results_poly$result_summary[, colnames_overlap], 
                     results_df1[, colnames_overlap],
                     results_df2[, colnames_overlap])

results_all = add_bound(results_all)

```

```{r fig.height=4, fig.width=9}
p1 <- plot_estimations_uHAL_gam_poly_noBT(results_all,save_plot = here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_compare_estimates.png")) )
```

```{r fig.height=9, fig.width=6}
p <- plot_performances_uHAL_gam_poly_noBT(results_all,save_plot = here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_compare_performances.png")) )
```



