
### CV HAL
```{r}
load(here("data", "rdata", paste0("02_simu_V3_sys", sn, "_", nn, "_CV.RData")))
```

#### results
```{r , fig.width=6, fig.height=4}
set.seed(123)

cat(paste0("CV selected lambda (from one sample): ", unique(psi_10pnt$lambda)))


p1 <- plot_perforences_1lambda_alla(psi_10pnt, z_para=1, est_plot_only = T) +
  labs(title = "z=1") + theme(plot.title = element_text(hjust = 0.5))
p0 <- plot_perforences_1lambda_alla(psi_10pnt, z_para=0, est_plot_only = T) +
  labs(title = "z=0") + theme(plot.title = element_text(hjust = 0.5))

p <- grid.arrange(p1, p0, nrow=1,
                  top = textGrob(paste0("Average Treatment Effect,  E[Y|a,z] - E[Y|0,z]",
                                         gp=gpar(fontface = 'bold')))) # gp=gpar(fontsize=11, fontface = 'bold')

ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z_n", nn ,"_1_cv.png")), p)
```

#### 1000 repetition 
```{r , fig.width=6, fig.height=7}
set.seed(123)
cat(paste0("The average of CV selected lambdas (from 1000 sample): ", mean(simu_results$result_summary$lambda)))

cat("z=1:")
p1_list <- plot_perforences_1lambda_alla(simu_results$result_summary, z_para=1, plot_list=F, add_oracal=T)
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z1", "_n", nn ,"_B_cv.png")), p1_list)

cat("z=0:")
p0_list <- plot_perforences_1lambda_alla(simu_results$result_summary, z_para=0, plot_list=F, add_oracal=T)
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z0", "_n", nn ,"_B_cv.png")), p0_list)

simu_results_CV <- simu_results$result_summary
simu_results_CV$method = "CV"
```

```{r , fig.width=6, fig.height=4}
p1 <- estimation_qqplot(results_list = simu_results$all_results, z_para = 1)
p1
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z1", "_n", nn ,"_B_cv_qq.png")), p1)

p0 <- estimation_qqplot(results_list = simu_results$all_results, z_para = 0)
p0
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z0", "_n", nn ,"_B_cv_qq.png")), p0)

```




### Globally Undersmoothed HAL
```{r}
load(here("data", "rdata", paste0("02_simu_V3_sys", sn, "_", nn, "_U.RData")))
```

#### results
```{r, fig.width=6, fig.height=4}
set.seed(123)

cat(paste0("Undersmoothed lambda: ", mean(psi_10pnt$lambda), 
             "\n which is ", mean(psi_10pnt$lambda)/mean(psi_10pnt$CV_lambda), " * lambda_CV"))
  
  
p1 <- plot_perforences_1lambda_alla(psi_10pnt, z_para=1, est_plot_only = T) +
    labs(title = "z=1") + theme(plot.title = element_text(hjust = 0.5))
p0 <- plot_perforences_1lambda_alla(psi_10pnt, z_para=0, est_plot_only = T) +
    labs(title = "z=0") + theme(plot.title = element_text(hjust = 0.5))
  
p <- grid.arrange(p1, p0, nrow=1,
                    top = textGrob(paste0("Average Treatment Effect,  E[Y|a,z] - E[Y|0,z]",
                                           gp=gpar(fontface = 'bold')))) # gp=gpar(fontsize=11, fontface = 'bold')
  
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z_n", nn ,"_1_u.png")), p)

```

#### 1000 repetition 
```{r , fig.width=6, fig.height=7}
set.seed(123)
  
avg_u_scaler <- mean(simu_results$result_summary$lambda)/mean(simu_results$result_summary$CV_lambda)
  
cat(paste0("The average of unsersmoothed lambda (from 1000 sample): ", mean(simu_results$result_summary$lambda),
             "\n which is ", avg_u_scaler, " * the average of 1000 lambda_CV"))
  
  
cat("z=1:")
p1_list <- plot_perforences_1lambda_alla(simu_results$result_summary, z_para=1, plot_list=F, add_oracal=T)
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z1", "_n", nn ,"_B_u.png")), p1_list)
  
cat("z=0:")
p0_list <- plot_perforences_1lambda_alla(simu_results$result_summary, z_para=0, plot_list=F, add_oracal=T)
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z0", "_n", nn ,"_B_u.png")), p0_list)
  
simu_results_U <- simu_results$result_summary
simu_results_U$method = "Undersmoothing"
```

```{r , fig.width=6, fig.height=4}
  p1 <- estimation_qqplot(results_list = simu_results$all_results, z_para = 1)
  p1
  ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z1", "_n", nn ,"_B_u_qq.png")), p1)
  
  p0 <- estimation_qqplot(results_list = simu_results$all_results, z_para = 0)
  p0
  ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z0", "_n", nn ,"_B_u_qq.png")), p0)
```


### CV vs Undersmoothing
```{r, fig.width=6, fig.height=7}
source(here("scripts", "scripts_v3", "1_visual_functions.R"))

simu_results_CV_U <- rbind(simu_results_CV, simu_results_U)

cat("z=1:")
p1 <- plot_perforences_cv_u_alla(simu_results_CV_U, z_para=1)
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z1", "_n", nn ,"_cv_vs_u.png")), p1)


cat("z=0:")
p0 <- plot_perforences_cv_u_alla(simu_results_CV_U, z_para=0)
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z1", "_n", nn ,"_cv_vs_u.png")), p0)

```


### Oevr a grid of lambda scalers

```{r}
load(here("data", "rdata", paste0("02_simu_V3_sys", sn, "_", nn, "_grid.RData")))
source(here("scripts", "scripts_v3", "1_visual_functions.R"))
```

```{r , fig.height=5.5, fig.width=5.5}
plot_perforences_alllambda_1a(simu_results_all, a_para = 0.5, z_para = 1, add_oracal=T, u_scaler=avg_u_scaler)
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z0", "_n", nn ,"_B_grid_a05_z1.png")))
```

```{r , fig.height=5.5, fig.width=5.5}
plot_perforences_alllambda_1a(simu_results_all, a_para = 2, z_para = 1, add_oracal=T, u_scaler=avg_u_scaler)
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z0", "_n", nn ,"_B_grid_a2_z1.png")))
```

```{r , fig.height=5.5, fig.width=5.5}
plot_perforences_alllambda_1a(simu_results_all, a_para = 2.5, z_para = 1, add_oracal=T, u_scaler=avg_u_scaler)
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z0", "_n", nn ,"_B_grid_a25_z1.png")))
```

```{r , fig.height=5.5, fig.width=5.5}
plot_perforences_alllambda_1a(simu_results_all, a_para = 3, z_para = 1, add_oracal=T, u_scaler=avg_u_scaler)
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z0", "_n", nn ,"_B_grid_a3_z1.png")))
```

```{r , fig.height=5.5, fig.width=5.5}
plot_perforences_alllambda_1a(simu_results_all, a_para = 4, z_para = 1, add_oracal=T, u_scaler=avg_u_scaler)
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z0", "_n", nn ,"_B_grid_a4_z1.png")))
```

```{r , fig.height=5.5, fig.width=5.5}
plot_perforences_alllambda_1a(simu_results_all, a_para = 5, z_para = 1, add_oracal=T, u_scaler=avg_u_scaler)
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z0", "_n", nn ,"_B_grid_a5_z1.png")))
```


```{r , fig.height=5.5, fig.width=5.5}
plot_perforences_alllambda_1a(simu_results_all, a_para = 0.5, z_para = 0, add_oracal=T, u_scaler=avg_u_scaler)
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z0", "_n", nn ,"_B_grid_a05_z0.png")))
```

```{r , fig.height=5.5, fig.width=5.5}
plot_perforences_alllambda_1a(simu_results_all, a_para = 2, z_para = 0, add_oracal=T, u_scaler=avg_u_scaler)
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z0", "_n", nn ,"_B_grid_a2_z0.png")))
```

```{r , fig.height=5.5, fig.width=5.5}
plot_perforences_alllambda_1a(simu_results_all, a_para = 2.5, z_para = 0, add_oracal=T, u_scaler=avg_u_scaler)
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z0", "_n", nn ,"_B_grid_a25_z0.png")))
```

```{r , fig.height=5.5, fig.width=5.5}
plot_perforences_alllambda_1a(simu_results_all, a_para = 3, z_para = 0, add_oracal=T, u_scaler=avg_u_scaler)
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z0", "_n", nn ,"_B_grid_a3_z0.png")))
```

```{r , fig.height=5.5, fig.width=5.5}
plot_perforences_alllambda_1a(simu_results_all, a_para = 4, z_para = 0, add_oracal=T, u_scaler=avg_u_scaler)
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z0", "_n", nn ,"_B_grid_a4_z0.png")))
```

```{r , fig.height=5.5, fig.width=5.5}
plot_perforences_alllambda_1a(simu_results_all, a_para = 5, z_para = 0, add_oracal=T, u_scaler=avg_u_scaler)
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_z0", "_n", nn ,"_B_grid_a5_z0.png")))
```

