
```{r fig.width=10, fig.height=7}
obs <- DGS(n=10000)
print(summary(obs))
  
# check positivity violations
cat("Summary of A given W < -1:")
summary(obs$A[obs$W < -1])
cat("Summary of A given -1 < W <= 0:")
summary(obs$A[-1 <= obs$W & obs$W < 0])
cat("Summary of A given 0 < W <= 1:")
summary(obs$A[0 <= obs$W & obs$W < 1])
cat("Summary of A given 1 < W:")
summary(obs$A[1 <= obs$W])


p1 = ggplot(obs, aes(W)) + geom_histogram(stat="bin",aes(y=..density..), color='lightyellow', fill='lightyellow') + geom_density(lwd=1) + theme_bw() + labs(y='Density')
p2 = ggplot(obs, aes(A)) + geom_histogram(stat="bin",aes(y=..density..), color='lightyellow', fill='lightyellow') + geom_density(lwd=1) + theme_bw() + labs(y='Density')
p3 = ggplot(obs %>% group_by(Y) %>% summarise(count = n()) %>% mutate(Proportion = count / 10000), 
            aes(x = Y, y = Proportion)) + geom_bar(stat = "identity", fill='lightyellow', color='grey') + theme_bw()
p4 = ggplot(obs, aes(W, A)) + geom_point() + theme_bw()
p5 = ggplot(obs, aes(W, Y)) + geom_point() + theme_bw()
p6 = ggplot(obs, aes(A, Y)) + geom_point() + theme_bw()

p <- grid.arrange(p1, p2, p3, p4, p5, p6, 
                  nrow=2, ncol=3,
                  top = textGrob(sprintf('Variable distributions of simulation %i', sn), 
                                   gp=gpar(fontsize=17)))
ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_EDAs.png")), p, width = 10, height = 6, dpi = 1000)
```


```{r fig.width=5, fig.height=4}
load(file=here("data", "rdata", paste0("02_simu_V5_sys", sn ,"_psi0.RData")))

ggplot() +
    geom_line(data=psi0_line, aes(x=a, y=psi0)) + 
    geom_point(data=psi0_pnt, aes(x=a, y=psi0)) + 
    labs(x="a", y="P_0(E[Y|a,W])",
         title = "True Average Treatment Effect, P_0(E[Y|a,W])") +
        theme(plot.title = element_text(hjust = 0.5),
              panel.grid.major.x = element_blank(),
              axis.text = element_text(size=7)) +
  theme_bw()

ggsave(here(getwd(), "plots", paste0("simu_sys", sn, "_psi0.png")),  width = 5, height = 4, dpi = 1000)

```


## n = 200
```{r}
nn=200
```

```{r}
load(here("data", "rdata", paste0("02_simu_V5_sys", sn, "_", nn, ".RData")))


cv_lambda = unique(results$result_summary$lambda[results$result_summary$method == 'CV'])
u_g_lambda = unique(results$result_summary$lambda[results$result_summary$method == 'U_G'])
u_g_scaler = unique(results$result_summary$lambda_scaler[results$result_summary$method == 'U_G'])

eval_points = seq(0,5,0.5)
u_l_lambdas = rep(NA, length(eval_points))
u_l_scalers = rep(NA, length(eval_points))

for (i in 1:length(eval_points)) {
  u_l_lambdas[i] = unique(results$result_summary$lambda[results$result_summary$method == 'U_L' & results$result_summary$a == eval_points[i]])
  u_l_scalers[i] = unique(results$result_summary$lambda_scaler[results$result_summary$method == 'U_L' & results$result_summary$a == eval_points[i]])
}

cat(sprintf(' The average lambda of CV-HAL: %0.4f (= 1 * lambda_CV )', cv_lambda))
cat(sprintf(' The average lambda of globally undersmoothed HAL: %0.4f (= %0.4f * lambda_CV )', u_g_lambda, u_g_scaler))
cat(paste0(' The average lambdatime of locally undersmoothed HAL:',
           '       ', paste0(round(u_l_lambdas, 4), collapse = ", "),
           '   (= [', paste0(round(u_l_scalers, 4), collapse = ", "), '] * lambda_CV'))

cat(sprintf(' The average fitting time for CV-HAL: %0.4f seconds', mean(results$result_summary$hal_fit_time[results$result_summary$method=='CV'])))
cat(sprintf(' The average fitting time for globally undersmoothed HAL: %0.4f seconds', mean(results$result_summary$hal_fit_time[results$result_summary$method=='U_G'])))
cat(sprintf(' The average fitting time for locally undersmoothed HAL: %0.4f seconds', mean(results$result_summary$hal_fit_time[results$result_summary$method=='U_L'])))


```

```{r fig.height=9, fig.width=9}
p <- plot_performences_cv_u_gl_alla(df = results$result_summary, save_plot = here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_performences.png")))
```

```{r fig.height=4, fig.width=12}
p <- estimation_qqplot_cv_u_gl_alla(results_list = results, save_plot = here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_QQplots.png")))
plot(p)
```

```{r}
load(here("data", "rdata", paste0("02_simu_V5_sys", sn, "_", nn, "_poly.RData")))
load(here("data", "rdata", paste0("02_simu_V5_sys", sn, "_", nn, "_GAM.RData")))

results_poly$result_summary$method = "Poly"

results_all <- rbind(results_gam$result_summary, 
                     results_poly$result_summary[, names(results_poly$result_summary)], 
                     results$result_summary[, names(results_poly$result_summary)])
```

```{r fig.height=4, fig.width=12}
p1 <- plot_estimations_uHAL_gam_poly(results_all,save_plot = here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_compare_estimates.png")) )
```

```{r fig.height=9, fig.width=8}
p <- plot_performances_uHAL_gam_poly(results_all,save_plot = here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_compare_performances.png")) )
```

## n = 500
```{r}
nn=500
```

```{r}
load(here("data", "rdata", paste0("02_simu_V5_sys", sn, "_", nn, ".RData")))


cv_lambda = unique(results$result_summary$lambda[results$result_summary$method == 'CV'])
u_g_lambda = unique(results$result_summary$lambda[results$result_summary$method == 'U_G'])
u_g_scaler = unique(results$result_summary$lambda_scaler[results$result_summary$method == 'U_G'])

eval_points = seq(0,5,0.5)
u_l_lambdas = rep(NA, length(eval_points))
u_l_scalers = rep(NA, length(eval_points))
for (i in 1:length(eval_points)) {
  u_l_lambdas[i] = unique(results$result_summary$lambda[results$result_summary$method == 'U_L' & results$result_summary$a == eval_points[i]])
  u_l_scalers[i] = unique(results$result_summary$lambda_scaler[results$result_summary$method == 'U_L' & results$result_summary$a == eval_points[i]])
}

cat(sprintf(' The average lambda of CV-HAL: %0.4f (= 1 * lambda_CV )', cv_lambda))
cat(sprintf(' The average lambda of globally undersmoothed HAL: %0.4f (= %0.4f * lambda_CV )', u_g_lambda, u_g_scaler))
cat(paste0(' The average lambdatime of locally undersmoothed HAL:',
           '       ', paste0(round(u_l_lambdas, 4), collapse = ", "),
           '   (= [', paste0(round(u_l_scalers, 4), collapse = ", "), '] * lambda_CV'))

cat(sprintf(' The average fitting time for CV-HAL: %0.4f seconds', mean(results$result_summary$hal_fit_time[results$result_summary$method=='CV'])))
cat(sprintf(' The average fitting time for globally undersmoothed HAL: %0.4f seconds', mean(results$result_summary$hal_fit_time[results$result_summary$method=='U_G'])))
cat(sprintf(' The average fitting time for locally undersmoothed HAL: %0.4f seconds', mean(results$result_summary$hal_fit_time[results$result_summary$method=='U_L'])))


```

```{r fig.height=9, fig.width=9}
p <- plot_performences_cv_u_gl_alla(df = results$result_summary, save_plot = here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_performences.png")))
```

```{r fig.height=4, fig.width=12}
p <- estimation_qqplot_cv_u_gl_alla(results_list = results, save_plot = here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_QQplots.png")))
plot(p)
```

```{r}
load(here("data", "rdata", paste0("02_simu_V5_sys", sn, "_", nn, "_poly.RData")))
load(here("data", "rdata", paste0("02_simu_V5_sys", sn, "_", nn, "_GAM.RData")))

results_poly$result_summary$method = "Poly"

results_all <- rbind(results_gam$result_summary, 
                     results_poly$result_summary[, names(results_poly$result_summary)], 
                     results$result_summary[, names(results_poly$result_summary)])
```


```{r fig.height=4, fig.width=12}
p1 <- plot_estimations_uHAL_gam_poly(results_all,save_plot = here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_compare_estimates.png")) )
```

```{r fig.height=9, fig.width=8}
p <- plot_performances_uHAL_gam_poly(results_all,save_plot = here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_compare_performances.png")) )
```

## n = 1000
```{r}
nn=1000
```

```{r}
load(here("data", "rdata", paste0("02_simu_V5_sys", sn, "_", nn, ".RData")))


cv_lambda = unique(results$result_summary$lambda[results$result_summary$method == 'CV'])
u_g_lambda = unique(results$result_summary$lambda[results$result_summary$method == 'U_G'])
u_g_scaler = unique(results$result_summary$lambda_scaler[results$result_summary$method == 'U_G'])

eval_points = seq(0,5,0.5)
u_l_lambdas = rep(NA, length(eval_points))
u_l_scalers = rep(NA, length(eval_points))
for (i in 1:length(eval_points)) {
  u_l_lambdas[i] = unique(results$result_summary$lambda[results$result_summary$method == 'U_L' & results$result_summary$a == eval_points[i]])
  u_l_scalers[i] = unique(results$result_summary$lambda_scaler[results$result_summary$method == 'U_L' & results$result_summary$a == eval_points[i]])
}

cat(sprintf(' The average lambda of CV-HAL: %0.4f (= 1 * lambda_CV )', cv_lambda))
cat(sprintf(' The average lambda of globally undersmoothed HAL: %0.4f (= %0.4f * lambda_CV )', u_g_lambda, u_g_scaler))
cat(paste0(' The average lambdatime of locally undersmoothed HAL:',
           '       ', paste0(round(u_l_lambdas, 4), collapse = ", "),
           '   (= [', paste0(round(u_l_scalers, 4), collapse = ", "), '] * lambda_CV'))

cat(sprintf(' The average fitting time for CV-HAL: %0.4f seconds', mean(results$result_summary$hal_fit_time[results$result_summary$method=='CV'])))
cat(sprintf(' The average fitting time for globally undersmoothed HAL: %0.4f seconds', mean(results$result_summary$hal_fit_time[results$result_summary$method=='U_G'])))
cat(sprintf(' The average fitting time for locally undersmoothed HAL: %0.4f seconds', mean(results$result_summary$hal_fit_time[results$result_summary$method=='U_L'])))


```

```{r fig.height=9, fig.width=9}
p <- plot_performences_cv_u_gl_alla(df = results$result_summary, save_plot = here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_performences.png")))
```

```{r fig.height=4, fig.width=12}
p <- estimation_qqplot_cv_u_gl_alla(results_list = results, save_plot = here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_QQplots.png")))
plot(p)
```

```{r}
load(here("data", "rdata", paste0("02_simu_V5_sys", sn, "_", nn, "_poly.RData")))
load(here("data", "rdata", paste0("02_simu_V5_sys", sn, "_", nn, "_GAM.RData")))

results_poly$result_summary$method = "Poly"

results_all <- rbind(results_gam$result_summary, 
                     results_poly$result_summary[, names(results_poly$result_summary)], 
                     results$result_summary[, names(results_poly$result_summary)])
```

```{r fig.height=4, fig.width=12}
p1 <- plot_estimations_uHAL_gam_poly(results_all,save_plot = here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_compare_estimates.png")) )
```

```{r fig.height=9, fig.width=8}
p <- plot_performances_uHAL_gam_poly(results_all,save_plot = here(getwd(), "plots", paste0("simu_sys", sn, "_n", n, "_compare_performances.png")) )
```
